# Generated by Django 4.0.4 on 2022-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_no',
            field=models.CharField(db_column='Card_No', max_length=19),
        ),
    ]
